#!/usr/bin/env python3
"""Generate no-op OpenGL 1.x stubs for the PS Vita software-only build of dsda-doom.

The Vita build never creates a GL context (the renderer is forced to software),
but the GL renderer code is still compiled and linked. These stubs satisfy the
linker for every GL 1.x entry point dsda-doom references directly.
Usage: gen_gl_stubs.py <SDL_opengl.h> <used-names.txt> <out.c>
"""
import re, sys

hdr, used_path, out = sys.argv[1:4]
text = open(hdr, encoding="utf-8", errors="replace").read()
text = re.sub(r"\\\n", " ", text)
used = {l.strip() for l in open(used_path) if l.strip()}

proto = re.compile(r"GLAPI\s+([^;()]*?)\s*GLAPIENTRY\s+(gl[A-Z]\w*)\s*\(([^)]*)\)\s*;", re.S)
found = {}
for ret, name, args in proto.findall(text):
    if name in used and name not in found:
        found[name] = (" ".join(ret.split()), " ".join(args.split()))

def zero(ret):
    r = ret.replace("const", "").strip()
    if r == "void":
        return ""
    if "*" in r:
        return " return 0;"
    return " return (%s)0;" % ret

lines = [
    "/* Generated by tools/gen_gl_stubs.py - do not edit. */",
    "/* No-op OpenGL entry points for the software-only PS Vita build. */",
    "#include <SDL_opengl.h>",
    "",
]
for name in sorted(found):
    ret, args = found[name]
    if args.strip() == "":
        args = "void"
    lines.append("%s GLAPIENTRY %s(%s) {%s }" % (ret, name, args, zero(ret)))
open(out, "w").write("\n".join(lines) + "\n")

missing = sorted(used - set(found))
sys.stderr.write("stubbed %d, not in SDL_opengl.h: %s\n" % (len(found), " ".join(missing)))
