/* Generated by tools/gen_gl_stubs.py - do not edit. */
/* No-op OpenGL entry points for the software-only PS Vita build. */
#include <SDL_opengl.h>

void GLAPIENTRY glAlphaFunc(GLenum func, GLclampf ref) { }
void GLAPIENTRY glBegin(GLenum mode) { }
void GLAPIENTRY glBindTexture(GLenum target, GLuint texture) { }
void GLAPIENTRY glBlendFunc(GLenum sfactor, GLenum dfactor) { }
void GLAPIENTRY glClear(GLbitfield mask) { }
void GLAPIENTRY glClearColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha) { }
void GLAPIENTRY glClearDepth(GLclampd depth) { }
void GLAPIENTRY glColor3f(GLfloat red, GLfloat green, GLfloat blue) { }
void GLAPIENTRY glColor4f(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) { }
void GLAPIENTRY glColor4fv(const GLfloat *v) { }
void GLAPIENTRY glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha) { }
void GLAPIENTRY glColorPointer(GLint size, GLenum type, GLsizei stride, const GLvoid *ptr) { }
void GLAPIENTRY glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height) { }
void GLAPIENTRY glCullFace(GLenum mode) { }
void GLAPIENTRY glDeleteTextures(GLsizei n, const GLuint *textures) { }
void GLAPIENTRY glDepthFunc(GLenum func) { }
void GLAPIENTRY glDepthMask(GLboolean flag) { }
void GLAPIENTRY glDisable(GLenum cap) { }
void GLAPIENTRY glDisableClientState(GLenum cap) { }
void GLAPIENTRY glDrawArrays(GLenum mode, GLint first, GLsizei count) { }
void GLAPIENTRY glEnable(GLenum cap) { }
void GLAPIENTRY glEnableClientState(GLenum cap) { }
void GLAPIENTRY glEnd(void) { }
void GLAPIENTRY glFlush(void) { }
void GLAPIENTRY glGenTextures(GLsizei n, GLuint *textures) { }
void GLAPIENTRY glGetIntegerv(GLenum pname, GLint *params) { }
const GLubyte * GLAPIENTRY glGetString(GLenum name) { return 0; }
void GLAPIENTRY glGetTexImage(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels) { }
void GLAPIENTRY glGetTexLevelParameteriv(GLenum target, GLint level, GLenum pname, GLint *params) { }
void GLAPIENTRY glHint(GLenum target, GLenum mode) { }
void GLAPIENTRY glLoadIdentity(void) { }
void GLAPIENTRY glLoadMatrixf(const GLfloat *m) { }
void GLAPIENTRY glMatrixMode(GLenum mode) { }
void GLAPIENTRY glOrtho(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val) { }
void GLAPIENTRY glPixelStorei(GLenum pname, GLint param) { }
void GLAPIENTRY glPolygonOffset(GLfloat factor, GLfloat units) { }
void GLAPIENTRY glPopMatrix(void) { }
void GLAPIENTRY glPushMatrix(void) { }
void GLAPIENTRY glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels) { }
void GLAPIENTRY glRotatef(GLfloat angle, GLfloat x, GLfloat y, GLfloat z) { }
void GLAPIENTRY glScalef(GLfloat x, GLfloat y, GLfloat z) { }
void GLAPIENTRY glScissor(GLint x, GLint y, GLsizei width, GLsizei height) { }
void GLAPIENTRY glShadeModel(GLenum mode) { }
void GLAPIENTRY glStencilFunc(GLenum func, GLint ref, GLuint mask) { }
void GLAPIENTRY glStencilOp(GLenum fail, GLenum zfail, GLenum zpass) { }
void GLAPIENTRY glTexCoord2f(GLfloat s, GLfloat t) { }
void GLAPIENTRY glTexCoord2fv(const GLfloat *v) { }
void GLAPIENTRY glTexCoordPointer(GLint size, GLenum type, GLsizei stride, const GLvoid *ptr) { }
void GLAPIENTRY glTexEnvf(GLenum target, GLenum pname, GLfloat param) { }
void GLAPIENTRY glTexEnvi(GLenum target, GLenum pname, GLint param) { }
void GLAPIENTRY glTexGenf(GLenum coord, GLenum pname, GLfloat param) { }
void GLAPIENTRY glTexGenfv(GLenum coord, GLenum pname, const GLfloat *params) { }
void GLAPIENTRY glTexImage2D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels) { }
void GLAPIENTRY glTexParameterf(GLenum target, GLenum pname, GLfloat param) { }
void GLAPIENTRY glTexParameteri(GLenum target, GLenum pname, GLint param) { }
void GLAPIENTRY glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels) { }
void GLAPIENTRY glTranslatef(GLfloat x, GLfloat y, GLfloat z) { }
void GLAPIENTRY glVertex2f(GLfloat x, GLfloat y) { }
void GLAPIENTRY glVertex2i(GLint x, GLint y) { }
void GLAPIENTRY glVertex3f(GLfloat x, GLfloat y, GLfloat z) { }
void GLAPIENTRY glVertex3fv(const GLfloat *v) { }
void GLAPIENTRY glVertexPointer(GLint size, GLenum type, GLsizei stride, const GLvoid *ptr) { }
void GLAPIENTRY glViewport(GLint x, GLint y, GLsizei width, GLsizei height) { }
